import { createFileRoute } from '@tanstack/react-router';
import PageLayout from '../../../../layouts/PageLayout';
import type RaceDriverResult from '../../../../types/response/RaceDriverResult';
import { createColumnHelper } from '@tanstack/react-table';
import Table from '../../../../components/Table';

export const Route = createFileRoute('/seasons/$season/$grand-prix/')({
  component: SeasonGrandPrixPage,
});

function SeasonGrandPrixPage() {
  const title = ``;

  return (
    <PageLayout title={title}>
      <main className="flex flex-col gap-4 w-full">
        <Table columns={columns} data={data} />
      </main>
    </PageLayout>
  );
}

// export columns from a sibling file.
const columnHelper = createColumnHelper<RaceDriverResult>();

const columns = [
  columnHelper.accessor('positionNumber', {
    header: '',
    cell: (info) => info.getValue() || '-',
  }),
  columnHelper.accessor('driverId', {
    header: '',
    cell: ({ getValue, row: { original } }) => (
      <div>
        <span>{getValue()}</span>
        <div>
          <div>
            <span>{original.driverNumber}</span>
            <p className="p-0">{original.constructorId}</p>
          </div>
        </div>
      </div>
    ),
  }),
  columnHelper.accessor('fastestLap', {
    header: 'Best Lap',
    cell: ({ row: { original } }) =>
      fastestLaps.find((fl) => original.driverId === fl.driverId)?.time || '-',
    meta: {
      textAlign: 'center',
    },
  }),
  columnHelper.accessor('laps', {
    header: 'Laps',
    cell: (info) => info.getValue() || '-',
    meta: {
      textAlign: 'center',
    },
  }),
  columnHelper.accessor('time', {
    header: 'Race Time',
    cell: ({ getValue, row: { original } }) =>
      original.positionNumber === 1
        ? getValue()
        : original.gap || original.reasonRetired || '-',
    meta: {
      textAlign: 'right',
    },
  }),
];

const data: RaceDriverResult[] = [
  {
    positionDisplayOrder: 1,
    positionNumber: 1,
    positionText: '1',
    driverNumber: '10',
    driverId: 'pierre-gasly',
    constructorId: 'alphatauri',
    engineManufacturerId: 'honda',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 53,
    time: '1:47:06.056',
    timeMillis: 6426056,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: null,
    gapMillis: null,
    gapLaps: null,
    interval: null,
    intervalMillis: null,
    reasonRetired: null,
    points: 25,
    polePosition: false,
    qualificationPositionNumber: 10,
    qualificationPositionText: '10',
    gridPositionNumber: 10,
    gridPositionText: '10',
    positionsGained: 9,
    pitStops: 2,
    fastestLap: false,
    driverOfTheDay: true,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 2,
    positionNumber: 2,
    positionText: '2',
    driverNumber: '55',
    driverId: 'carlos-sainz-jr',
    constructorId: 'mclaren',
    engineManufacturerId: 'renault',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 53,
    time: '1:47:06.471',
    timeMillis: 6426471,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: '+0.415',
    gapMillis: 415,
    gapLaps: null,
    interval: '+0.415',
    intervalMillis: 415,
    reasonRetired: null,
    points: 18,
    polePosition: false,
    qualificationPositionNumber: 3,
    qualificationPositionText: '3',
    gridPositionNumber: 3,
    gridPositionText: '3',
    positionsGained: 1,
    pitStops: 2,
    fastestLap: false,
    driverOfTheDay: false,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 3,
    positionNumber: 3,
    positionText: '3',
    driverNumber: '18',
    driverId: 'lance-stroll',
    constructorId: 'racing-point',
    engineManufacturerId: 'bwt-mercedes',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 53,
    time: '1:47:09.414',
    timeMillis: 6429414,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: '+3.358',
    gapMillis: 3358,
    gapLaps: null,
    interval: '+2.943',
    intervalMillis: 2943,
    reasonRetired: null,
    points: 15,
    polePosition: false,
    qualificationPositionNumber: 8,
    qualificationPositionText: '8',
    gridPositionNumber: 8,
    gridPositionText: '8',
    positionsGained: 5,
    pitStops: 1,
    fastestLap: false,
    driverOfTheDay: false,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 4,
    positionNumber: 4,
    positionText: '4',
    driverNumber: '4',
    driverId: 'lando-norris',
    constructorId: 'mclaren',
    engineManufacturerId: 'renault',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 53,
    time: '1:47:12.056',
    timeMillis: 6432056,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: '+6.000',
    gapMillis: 6000,
    gapLaps: null,
    interval: '+2.642',
    intervalMillis: 2642,
    reasonRetired: null,
    points: 12,
    polePosition: false,
    qualificationPositionNumber: 6,
    qualificationPositionText: '6',
    gridPositionNumber: 6,
    gridPositionText: '6',
    positionsGained: 2,
    pitStops: 2,
    fastestLap: false,
    driverOfTheDay: false,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 5,
    positionNumber: 5,
    positionText: '5',
    driverNumber: '77',
    driverId: 'valtteri-bottas',
    constructorId: 'mercedes',
    engineManufacturerId: 'mercedes',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 53,
    time: '1:47:13.164',
    timeMillis: 6433164,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: '+7.108',
    gapMillis: 7108,
    gapLaps: null,
    interval: '+1.108',
    intervalMillis: 1108,
    reasonRetired: null,
    points: 10,
    polePosition: false,
    qualificationPositionNumber: 2,
    qualificationPositionText: '2',
    gridPositionNumber: 2,
    gridPositionText: '2',
    positionsGained: -3,
    pitStops: 2,
    fastestLap: false,
    driverOfTheDay: false,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 6,
    positionNumber: 6,
    positionText: '6',
    driverNumber: '3',
    driverId: 'daniel-ricciardo',
    constructorId: 'renault',
    engineManufacturerId: 'renault',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 53,
    time: '1:47:14.447',
    timeMillis: 6434447,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: '+8.391',
    gapMillis: 8391,
    gapLaps: null,
    interval: '+1.283',
    intervalMillis: 1283,
    reasonRetired: null,
    points: 8,
    polePosition: false,
    qualificationPositionNumber: 7,
    qualificationPositionText: '7',
    gridPositionNumber: 7,
    gridPositionText: '7',
    positionsGained: 1,
    pitStops: 2,
    fastestLap: false,
    driverOfTheDay: false,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 7,
    positionNumber: 7,
    positionText: '7',
    driverNumber: '44',
    driverId: 'lewis-hamilton',
    constructorId: 'mercedes',
    engineManufacturerId: 'mercedes',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 53,
    time: '1:47:23.301',
    timeMillis: 6443301,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: '+17.245',
    gapMillis: 17245,
    gapLaps: null,
    interval: '+8.854',
    intervalMillis: 8854,
    reasonRetired: null,
    points: 7,
    polePosition: true,
    qualificationPositionNumber: 1,
    qualificationPositionText: '1',
    gridPositionNumber: 1,
    gridPositionText: '1',
    positionsGained: -6,
    pitStops: 3,
    fastestLap: true,
    driverOfTheDay: false,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 8,
    positionNumber: 8,
    positionText: '8',
    driverNumber: '31',
    driverId: 'esteban-ocon',
    constructorId: 'renault',
    engineManufacturerId: 'renault',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 53,
    time: '1:47:24.747',
    timeMillis: 6444747,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: '+18.691',
    gapMillis: 18691,
    gapLaps: null,
    interval: '+1.446',
    intervalMillis: 1446,
    reasonRetired: null,
    points: 4,
    polePosition: false,
    qualificationPositionNumber: 12,
    qualificationPositionText: '12',
    gridPositionNumber: 12,
    gridPositionText: '12',
    positionsGained: 4,
    pitStops: 2,
    fastestLap: false,
    driverOfTheDay: false,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 9,
    positionNumber: 9,
    positionText: '9',
    driverNumber: '26',
    driverId: 'daniil-kvyat',
    constructorId: 'alphatauri',
    engineManufacturerId: 'honda',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 53,
    time: '1:47:28.264',
    timeMillis: 6448264,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: '+22.208',
    gapMillis: 22208,
    gapLaps: null,
    interval: '+3.517',
    intervalMillis: 3517,
    reasonRetired: null,
    points: 2,
    polePosition: false,
    qualificationPositionNumber: 11,
    qualificationPositionText: '11',
    gridPositionNumber: 11,
    gridPositionText: '11',
    positionsGained: 2,
    pitStops: 2,
    fastestLap: false,
    driverOfTheDay: false,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 10,
    positionNumber: 10,
    positionText: '10',
    driverNumber: '11',
    driverId: 'sergio-perez',
    constructorId: 'racing-point',
    engineManufacturerId: 'bwt-mercedes',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 53,
    time: '1:47:29.280',
    timeMillis: 6449280,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: '+23.224',
    gapMillis: 23224,
    gapLaps: null,
    interval: '+1.016',
    intervalMillis: 1016,
    reasonRetired: null,
    points: 1,
    polePosition: false,
    qualificationPositionNumber: 4,
    qualificationPositionText: '4',
    gridPositionNumber: 4,
    gridPositionText: '4',
    positionsGained: -6,
    pitStops: 2,
    fastestLap: false,
    driverOfTheDay: false,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 11,
    positionNumber: 11,
    positionText: '11',
    driverNumber: '6',
    driverId: 'nicholas-latifi',
    constructorId: 'williams',
    engineManufacturerId: 'mercedes',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 53,
    time: '1:47:38.932',
    timeMillis: 6458932,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: '+32.876',
    gapMillis: 32876,
    gapLaps: null,
    interval: '+9.652',
    intervalMillis: 9652,
    reasonRetired: null,
    points: null,
    polePosition: false,
    qualificationPositionNumber: 20,
    qualificationPositionText: '20',
    gridPositionNumber: 20,
    gridPositionText: '20',
    positionsGained: 9,
    pitStops: 2,
    fastestLap: false,
    driverOfTheDay: false,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 12,
    positionNumber: 12,
    positionText: '12',
    driverNumber: '8',
    driverId: 'romain-grosjean',
    constructorId: 'haas',
    engineManufacturerId: 'ferrari',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 53,
    time: '1:47:41.220',
    timeMillis: 6461220,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: '+35.164',
    gapMillis: 35164,
    gapLaps: null,
    interval: '+2.288',
    intervalMillis: 2288,
    reasonRetired: null,
    points: null,
    polePosition: false,
    qualificationPositionNumber: 16,
    qualificationPositionText: '16',
    gridPositionNumber: 16,
    gridPositionText: '16',
    positionsGained: 4,
    pitStops: 2,
    fastestLap: false,
    driverOfTheDay: false,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 13,
    positionNumber: 13,
    positionText: '13',
    driverNumber: '7',
    driverId: 'kimi-raikkonen',
    constructorId: 'alfa-romeo',
    engineManufacturerId: 'ferrari',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 53,
    time: '1:47:42.368',
    timeMillis: 6462368,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: '+36.312',
    gapMillis: 36312,
    gapLaps: null,
    interval: '+1.148',
    intervalMillis: 1148,
    reasonRetired: null,
    points: null,
    polePosition: false,
    qualificationPositionNumber: 14,
    qualificationPositionText: '14',
    gridPositionNumber: 14,
    gridPositionText: '14',
    positionsGained: 1,
    pitStops: 2,
    fastestLap: false,
    driverOfTheDay: false,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 14,
    positionNumber: 14,
    positionText: '14',
    driverNumber: '63',
    driverId: 'george-russell',
    constructorId: 'williams',
    engineManufacturerId: 'mercedes',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 53,
    time: '1:47:42.649',
    timeMillis: 6462649,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: '+36.593',
    gapMillis: 36593,
    gapLaps: null,
    interval: '+0.281',
    intervalMillis: 281,
    reasonRetired: null,
    points: null,
    polePosition: false,
    qualificationPositionNumber: 19,
    qualificationPositionText: '19',
    gridPositionNumber: 19,
    gridPositionText: '19',
    positionsGained: 5,
    pitStops: 2,
    fastestLap: false,
    driverOfTheDay: false,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 15,
    positionNumber: 15,
    positionText: '15',
    driverNumber: '23',
    driverId: 'alexander-albon',
    constructorId: 'red-bull',
    engineManufacturerId: 'honda',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 53,
    time: '1:47:43.589',
    timeMillis: 6463589,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: '+37.533',
    gapMillis: 37533,
    gapLaps: null,
    interval: '+0.940',
    intervalMillis: 940,
    reasonRetired: null,
    points: null,
    polePosition: false,
    qualificationPositionNumber: 9,
    qualificationPositionText: '9',
    gridPositionNumber: 9,
    gridPositionText: '9',
    positionsGained: -6,
    pitStops: 2,
    fastestLap: false,
    driverOfTheDay: false,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 16,
    positionNumber: 16,
    positionText: '16',
    driverNumber: '99',
    driverId: 'antonio-giovinazzi',
    constructorId: 'alfa-romeo',
    engineManufacturerId: 'ferrari',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 53,
    time: '1:48:01.255',
    timeMillis: 6481255,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: '+55.199',
    gapMillis: 55199,
    gapLaps: null,
    interval: '+17.666',
    intervalMillis: 17666,
    reasonRetired: null,
    points: null,
    polePosition: false,
    qualificationPositionNumber: 18,
    qualificationPositionText: '18',
    gridPositionNumber: 18,
    gridPositionText: '18',
    positionsGained: 2,
    pitStops: 3,
    fastestLap: false,
    driverOfTheDay: false,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 17,
    positionNumber: null,
    positionText: 'DNF',
    driverNumber: '33',
    driverId: 'max-verstappen',
    constructorId: 'red-bull',
    engineManufacturerId: 'honda',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 30,
    time: null,
    timeMillis: null,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: null,
    gapMillis: null,
    gapLaps: null,
    interval: null,
    intervalMillis: null,
    reasonRetired: 'Power unit',
    points: null,
    polePosition: false,
    qualificationPositionNumber: 5,
    qualificationPositionText: '5',
    gridPositionNumber: 5,
    gridPositionText: '5',
    positionsGained: null,
    pitStops: 2,
    fastestLap: false,
    driverOfTheDay: false,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 18,
    positionNumber: null,
    positionText: 'DNF',
    driverNumber: '16',
    driverId: 'charles-leclerc',
    constructorId: 'ferrari',
    engineManufacturerId: 'ferrari',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 23,
    time: null,
    timeMillis: null,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: null,
    gapMillis: null,
    gapLaps: null,
    interval: null,
    intervalMillis: null,
    reasonRetired: 'Accident',
    points: null,
    polePosition: false,
    qualificationPositionNumber: 13,
    qualificationPositionText: '13',
    gridPositionNumber: 13,
    gridPositionText: '13',
    positionsGained: null,
    pitStops: 1,
    fastestLap: false,
    driverOfTheDay: false,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 19,
    positionNumber: null,
    positionText: 'DNF',
    driverNumber: '20',
    driverId: 'kevin-magnussen',
    constructorId: 'haas',
    engineManufacturerId: 'ferrari',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 17,
    time: null,
    timeMillis: null,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: null,
    gapMillis: null,
    gapLaps: null,
    interval: null,
    intervalMillis: null,
    reasonRetired: 'Power unit',
    points: null,
    polePosition: false,
    qualificationPositionNumber: 15,
    qualificationPositionText: '15',
    gridPositionNumber: 15,
    gridPositionText: '15',
    positionsGained: null,
    pitStops: 1,
    fastestLap: false,
    driverOfTheDay: false,
    grandSlam: false,
  },
  {
    positionDisplayOrder: 20,
    positionNumber: null,
    positionText: 'DNF',
    driverNumber: '5',
    driverId: 'sebastian-vettel',
    constructorId: 'ferrari',
    engineManufacturerId: 'ferrari',
    tyreManufacturerId: 'pirelli',
    sharedCar: false,
    laps: 6,
    time: null,
    timeMillis: null,
    timePenalty: null,
    timePenaltyMillis: null,
    gap: null,
    gapMillis: null,
    gapLaps: null,
    interval: null,
    intervalMillis: null,
    reasonRetired: 'Brakes',
    points: null,
    polePosition: false,
    qualificationPositionNumber: 17,
    qualificationPositionText: '17',
    gridPositionNumber: 17,
    gridPositionText: '17',
    positionsGained: null,
    pitStops: 0,
    fastestLap: false,
    driverOfTheDay: false,
    grandSlam: false,
  },
];

const fastestLaps = [
  {
    positionDisplayOrder: 1,
    positionNumber: 1,
    positionText: '1',
    driverNumber: '44',
    driverId: 'lewis-hamilton',
    constructorId: 'mercedes',
    engineManufacturerId: 'mercedes',
    tyreManufacturerId: 'pirelli',
    lap: 34,
    time: '1:22.746',
    timeMillis: 82746,
    gap: null,
    gapMillis: null,
    interval: null,
    intervalMillis: null,
  },
  {
    positionDisplayOrder: 2,
    positionNumber: 2,
    positionText: '2',
    driverNumber: '55',
    driverId: 'carlos-sainz-jr',
    constructorId: 'mclaren',
    engineManufacturerId: 'renault',
    tyreManufacturerId: 'pirelli',
    lap: 40,
    time: '1:23.882',
    timeMillis: 83882,
    gap: '+1.136',
    gapMillis: 1136,
    interval: '+1.136',
    intervalMillis: 1136,
  },
  {
    positionDisplayOrder: 3,
    positionNumber: 3,
    positionText: '3',
    driverNumber: '18',
    driverId: 'lance-stroll',
    constructorId: 'racing-point',
    engineManufacturerId: 'bwt-mercedes',
    tyreManufacturerId: 'pirelli',
    lap: 42,
    time: '1:23.897',
    timeMillis: 83897,
    gap: '+1.151',
    gapMillis: 1151,
    interval: '+0.015',
    intervalMillis: 15,
  },
  {
    positionDisplayOrder: 4,
    positionNumber: 4,
    positionText: '4',
    driverNumber: '3',
    driverId: 'daniel-ricciardo',
    constructorId: 'renault',
    engineManufacturerId: 'renault',
    tyreManufacturerId: 'pirelli',
    lap: 38,
    time: '1:23.898',
    timeMillis: 83898,
    gap: '+1.152',
    gapMillis: 1152,
    interval: '+0.001',
    intervalMillis: 1,
  },
  {
    positionDisplayOrder: 5,
    positionNumber: 5,
    positionText: '5',
    driverNumber: '77',
    driverId: 'valtteri-bottas',
    constructorId: 'mercedes',
    engineManufacturerId: 'mercedes',
    tyreManufacturerId: 'pirelli',
    lap: 51,
    time: '1:23.961',
    timeMillis: 83961,
    gap: '+1.215',
    gapMillis: 1215,
    interval: '+0.063',
    intervalMillis: 63,
  },
  {
    positionDisplayOrder: 6,
    positionNumber: 6,
    positionText: '6',
    driverNumber: '10',
    driverId: 'pierre-gasly',
    constructorId: 'alphatauri',
    engineManufacturerId: 'honda',
    tyreManufacturerId: 'pirelli',
    lap: 34,
    time: '1:24.037',
    timeMillis: 84037,
    gap: '+1.291',
    gapMillis: 1291,
    interval: '+0.076',
    intervalMillis: 76,
  },
  {
    positionDisplayOrder: 7,
    positionNumber: 7,
    positionText: '7',
    driverNumber: '4',
    driverId: 'lando-norris',
    constructorId: 'mclaren',
    engineManufacturerId: 'renault',
    tyreManufacturerId: 'pirelli',
    lap: 50,
    time: '1:24.232',
    timeMillis: 84232,
    gap: '+1.486',
    gapMillis: 1486,
    interval: '+0.195',
    intervalMillis: 195,
  },
  {
    positionDisplayOrder: 8,
    positionNumber: 8,
    positionText: '8',
    driverNumber: '11',
    driverId: 'sergio-perez',
    constructorId: 'racing-point',
    engineManufacturerId: 'bwt-mercedes',
    tyreManufacturerId: 'pirelli',
    lap: 50,
    time: '1:24.336',
    timeMillis: 84336,
    gap: '+1.590',
    gapMillis: 1590,
    interval: '+0.104',
    intervalMillis: 104,
  },
  {
    positionDisplayOrder: 9,
    positionNumber: 9,
    positionText: '9',
    driverNumber: '63',
    driverId: 'george-russell',
    constructorId: 'williams',
    engineManufacturerId: 'mercedes',
    tyreManufacturerId: 'pirelli',
    lap: 39,
    time: '1:24.421',
    timeMillis: 84421,
    gap: '+1.675',
    gapMillis: 1675,
    interval: '+0.085',
    intervalMillis: 85,
  },
  {
    positionDisplayOrder: 10,
    positionNumber: 10,
    positionText: '10',
    driverNumber: '26',
    driverId: 'daniil-kvyat',
    constructorId: 'alphatauri',
    engineManufacturerId: 'honda',
    tyreManufacturerId: 'pirelli',
    lap: 44,
    time: '1:24.479',
    timeMillis: 84479,
    gap: '+1.733',
    gapMillis: 1733,
    interval: '+0.058',
    intervalMillis: 58,
  },
  {
    positionDisplayOrder: 11,
    positionNumber: 11,
    positionText: '11',
    driverNumber: '31',
    driverId: 'esteban-ocon',
    constructorId: 'renault',
    engineManufacturerId: 'renault',
    tyreManufacturerId: 'pirelli',
    lap: 52,
    time: '1:24.490',
    timeMillis: 84490,
    gap: '+1.744',
    gapMillis: 1744,
    interval: '+0.011',
    intervalMillis: 11,
  },
  {
    positionDisplayOrder: 12,
    positionNumber: 12,
    positionText: '12',
    driverNumber: '8',
    driverId: 'romain-grosjean',
    constructorId: 'haas',
    engineManufacturerId: 'ferrari',
    tyreManufacturerId: 'pirelli',
    lap: 48,
    time: '1:24.785',
    timeMillis: 84785,
    gap: '+2.039',
    gapMillis: 2039,
    interval: '+0.295',
    intervalMillis: 295,
  },
  {
    positionDisplayOrder: 13,
    positionNumber: 13,
    positionText: '13',
    driverNumber: '7',
    driverId: 'kimi-raikkonen',
    constructorId: 'alfa-romeo',
    engineManufacturerId: 'ferrari',
    tyreManufacturerId: 'pirelli',
    lap: 29,
    time: '1:24.835',
    timeMillis: 84835,
    gap: '+2.089',
    gapMillis: 2089,
    interval: '+0.050',
    intervalMillis: 50,
  },
  {
    positionDisplayOrder: 14,
    positionNumber: 14,
    positionText: '14',
    driverNumber: '99',
    driverId: 'antonio-giovinazzi',
    constructorId: 'alfa-romeo',
    engineManufacturerId: 'ferrari',
    tyreManufacturerId: 'pirelli',
    lap: 43,
    time: '1:24.856',
    timeMillis: 84856,
    gap: '+2.110',
    gapMillis: 2110,
    interval: '+0.021',
    intervalMillis: 21,
  },
  {
    positionDisplayOrder: 15,
    positionNumber: 15,
    positionText: '15',
    driverNumber: '23',
    driverId: 'alexander-albon',
    constructorId: 'red-bull',
    engineManufacturerId: 'honda',
    tyreManufacturerId: 'pirelli',
    lap: 48,
    time: '1:24.926',
    timeMillis: 84926,
    gap: '+2.180',
    gapMillis: 2180,
    interval: '+0.070',
    intervalMillis: 70,
  },
  {
    positionDisplayOrder: 16,
    positionNumber: 16,
    positionText: '16',
    driverNumber: '6',
    driverId: 'nicholas-latifi',
    constructorId: 'williams',
    engineManufacturerId: 'mercedes',
    tyreManufacturerId: 'pirelli',
    lap: 39,
    time: '1:24.999',
    timeMillis: 84999,
    gap: '+2.253',
    gapMillis: 2253,
    interval: '+0.073',
    intervalMillis: 73,
  },
  {
    positionDisplayOrder: 17,
    positionNumber: 17,
    positionText: '17',
    driverNumber: '33',
    driverId: 'max-verstappen',
    constructorId: 'red-bull',
    engineManufacturerId: 'honda',
    tyreManufacturerId: 'pirelli',
    lap: 10,
    time: '1:25.539',
    timeMillis: 85539,
    gap: '+2.793',
    gapMillis: 2793,
    interval: '+0.540',
    intervalMillis: 540,
  },
  {
    positionDisplayOrder: 18,
    positionNumber: 18,
    positionText: '18',
    driverNumber: '20',
    driverId: 'kevin-magnussen',
    constructorId: 'haas',
    engineManufacturerId: 'ferrari',
    tyreManufacturerId: 'pirelli',
    lap: 10,
    time: '1:25.787',
    timeMillis: 85787,
    gap: '+3.041',
    gapMillis: 3041,
    interval: '+0.248',
    intervalMillis: 248,
  },
  {
    positionDisplayOrder: 19,
    positionNumber: 19,
    positionText: '19',
    driverNumber: '16',
    driverId: 'charles-leclerc',
    constructorId: 'ferrari',
    engineManufacturerId: 'ferrari',
    tyreManufacturerId: 'pirelli',
    lap: 19,
    time: '1:26.026',
    timeMillis: 86026,
    gap: '+3.280',
    gapMillis: 3280,
    interval: '+0.239',
    intervalMillis: 239,
  },
];
