/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeasonsIndexRouteImport } from './routes/seasons/index'

const SeasonsIndexRoute = SeasonsIndexRouteImport.update({
  id: '/seasons/',
  path: '/seasons/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/seasons': typeof SeasonsIndexRoute
}
export interface FileRoutesByTo {
  '/seasons': typeof SeasonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/seasons/': typeof SeasonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/seasons'
  fileRoutesByTo: FileRoutesByTo
  to: '/seasons'
  id: '__root__' | '/seasons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SeasonsIndexRoute: typeof SeasonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seasons/': {
      id: '/seasons/'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SeasonsIndexRoute: SeasonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
