/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeasonsIndexRouteImport } from './routes/seasons/index'
import { Route as SeasonsSeasonIndexRouteImport } from './routes/seasons/$season/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsIndexRoute = SeasonsIndexRouteImport.update({
  id: '/seasons/',
  path: '/seasons/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsSeasonIndexRoute = SeasonsSeasonIndexRouteImport.update({
  id: '/seasons/$season/',
  path: '/seasons/$season/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/seasons': typeof SeasonsIndexRoute
  '/seasons/$season': typeof SeasonsSeasonIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/seasons': typeof SeasonsIndexRoute
  '/seasons/$season': typeof SeasonsSeasonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/seasons/': typeof SeasonsIndexRoute
  '/seasons/$season/': typeof SeasonsSeasonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/seasons' | '/seasons/$season'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/seasons' | '/seasons/$season'
  id: '__root__' | '/' | '/seasons/' | '/seasons/$season/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeasonsIndexRoute: typeof SeasonsIndexRoute
  SeasonsSeasonIndexRoute: typeof SeasonsSeasonIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/': {
      id: '/seasons/'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/$season/': {
      id: '/seasons/$season/'
      path: '/seasons/$season'
      fullPath: '/seasons/$season'
      preLoaderRoute: typeof SeasonsSeasonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeasonsIndexRoute: SeasonsIndexRoute,
  SeasonsSeasonIndexRoute: SeasonsSeasonIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
